In [1]:
##Question 1

from array import *
array_num = array('i', [1, 3, 5, 3, 7, 1, 9, 3])
print("array: "+str(array_num))
num_list = array_num.tolist()
print("Convert the said array to an ordinary list with the same items:")
print(num_list)

array: array('i', [1, 3, 5, 3, 7, 1, 9, 3])
Convert the said array to an ordinary list with the same items:
[1, 3, 5, 3, 7, 1, 9, 3]


In [2]:
##Question 2

import numpy as np
m = np.arange(6).reshape(2,3)
print("Original matrix:")
print(m)
result =  np.trace(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[0 1 2]
 [3 4 5]]
Condition number of the said matrix:
4


In [3]:
##Question 3
a = np.array([1, 2, 3, 4, 5])
x = 3
result = a[np.where((a>x))]
print(result)

  

[4 5]


In [4]:
##Question 4

A = np.array([1, 2, 3, 4, 5])
B = np.array([2, 3, 4, 5, 6])
   
print ("Array A: ", A)  
print ("Array B: ", B)  
   
out_arr = np.add(A, B)  
print ("Array C: ", out_arr)  

Array A:  [1 2 3 4 5]
Array B:  [2 3 4 5 6]
Array C:  [ 3  5  7  9 11]


In [8]:
##Question 5 

import numpy as np 
a = np.array ([[10, 15],[25, 30]])

x = a - a.mean(axis=1)

print(x)

[[ -2.5 -12.5]
 [ 12.5   2.5]]
